apiVersion: v1
kind: PersistentVolume
metadata:
  name: function-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /u/iot_data/iotstorage/user_actions
  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: function-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: function-pv